# -*- coding: utf-8 -*-
# this file is public domain - more free than free


from builtins import object


class bme_lists(object):
    rename_extras = ["cover.jpg", "foo_dr.txt", "vinyl.nfo"]

    # URL types (flac / ID3 WXXX name)
    wxxx = {
        "url_allmusic_artist_site": "ALLMUSIC_ARTIST",
        "url_allmusic_release_site": "ALLMUSIC_RELEASE",
        "url_allmusic_song_site": "ALLMUSIC_SONG",
        "url_bbc_artist_site": "BBC_ARTIST",
        "url_discogs_artist_site": "DISCOGS_ARTIST",
        "url_discogs_master_site": "DISCOGS_MASTER",
        "url_discogs_release_site": "DISCOGS_RELEASE",
        "url_download_free": "FREE_DOWNLOAD",
        "url_lyrics_site": "LYRICS_SITE",
        "url_other_database": "DATABASE",
        "url_wikidata_song_site": "WIKIDATA_SONG",
        "url_wikipedia_release_site": "WIKIPEDIA_RELEASE",
        "url_wikipedia_song_site": "WIKIPEDIA_SONG",
    }

    # these are tags we never accept
    # many of these should be renames instead of deletes
    bogus = [
        "accurateripdiscid",
        "accurateripresult",
        "analysis",
        "band",
        "catalog",
        "catalog_number",
        # "comments",
        "cuesheet",
        "description",
        "discogs-id",
        "discogs_price",
        # "encoder settings",
        "fingerprint",
        "format",
        "gracenoteextdata",
        "gracenotefileid",
        "hd tracks",  # just the url?
        "hdtracks",  # they aren't consistent
        "instrument",
        "intensity",
        "itunes_cddb_1",
        "itunesgapless",
        "itunesnorm",
        "medium",
        "mix",
        "musicbrainz_albumstatus",
        "musicip_puid",
        "orchestrator",
        "original album",
        "original artist",
        "originator_reference",
        "origreference",  # HDtracks, has saracon data
        "origtime",  # HDtracks
        "price",
        "rating",
        "recording",
        "source",
        "style",
        "styles",
        "tag_50_degree",
        "tag_50",
        "time_reference",
        "timereference",  # HD tracks
        "traktor4",
        "url_discogs_release_image",
        "vinylno.",
        "vocal",
        "waveformatextensible_channel_mask",
    ]

    # tags we know
    known = [
        "acoustid_fingerprint",
        "acoustid_id",
        "akm id",
        "album dynamic range",
        "album",
        "albumartist",
        "albumartistsort",
        "albumsort",
        "apra id",
        "arranger",
        "art direction",
        "artist",
        "artists",
        "artistsort",
        "ascap id",
        "asin",
        "audio",
        "balance",
        "barcode",
        "beatintensity",
        "bmi id",
        "booking",
        "bpm",
        "cash id",
        "catalognumber",
        "cd_qchan_isrc",
        "cddb",
        "cdtext_performer_album",
        "cdtext_performer_track",
        "cdtext_title",
        "chorus master",
        "codinghistory",  # HDtracks does this -- actually useful
        "comment",
        "compilation",
        "compiler",
        "composer",
        "composersort",
        "concertmaster",
        "conductor",
        "copyright",
        "country",
        "creative direction",
        "date",
        "dedication",
        "design",
        "design/illustration",
        "digitize_date",
        "digitize_info",
        "discnumber",
        "discsubtitle",
        "disctotal",
        "distributed",
        "djmixer",
        "dynamic range",
        "editor",
        "encoder",
        "engineer",
        "ensemble",
        "gema id",
        "genre",
        "graphic design",
        "grouping",
        "illustration",
        "instrument arranger",
        "isrc",
        "iswc",
        "itunescomm",
        "jasrac id",
        "key",
        "label",
        "language",
        "legal representation",
        "librettist",
        "license",
        "licensor",
        "liner notes",
        "lyricist",
        "lyrics",
        "mastering",
        "mcn",
        "media",
        "misc",
        "mixer",
        "mood",
        "musicbrainz_albumartistid",
        "musicbrainz_albumcomment",
        "musicbrainz_albumid",
        "musicbrainz_albumtype",
        "musicbrainz_artistid",
        "musicbrainz_discid",
        "musicbrainz_recordingid",
        "musicbrainz_releasegroupid",
        "musicbrainz_releasetrackid",
        "musicbrainz_trackid",
        "musicbrainz_trmid",
        "musicbrainz_workid",
        "organization",
        "original_album",
        "original_artist",
        "originaldate",
        "originalyear",  # new?
        "packaging",
        "performer",
        "performing orchestra",
        "phonographic copyright",
        "photography",
        "producer",
        "programming",
        "publisher",
        "publishing",
        "releasecountry",
        "releasestatus",
        "releasetype",
        "remixer",
        "replaygain_album_gain",
        "replaygain_album_peak",
        "replaygain_reference_loudness",
        "replaygain_track_gain",
        "replaygain_track_peak",
        "revised by",
        "samples from artist",
        "scale",
        "script",
        "sacem id",
        "sesac id",
        "socan id",
        "sound",
        "subtitle",
        "tag",
        "time_signature",
        "title",
        "titlesort",
        "toc",
        "totaldiscs",
        "totaltracks",
        "tracknumber",
        "tracktotal",
        "translator",
        "tuning",
        "vinyldigitizer",
        "vocal arranger",
        "work",
        "writer",
        "beat_intensity",
        "bpm_accuracy",
        "bpm_end",
        "bpm_start",
        "key_accuracy",
        "key_end",
        "key_start",
    ]

    for k, v in list(wxxx.items()):
        known.append(k)
    known = bogus + known

    # frequently incorrectly named tags
    rename = {
        "album_artist": "albumartist",
        "albumartist_credit": "albumartist",
        "artist_credit": "artist",
        "comments": "comment",
        "digitizer": "vinyldigitizer",
        "encoded by": "encoder",
        "encodedby": "encoder",
        "encoded_by": "encoder",
        "encoder settings": "encoder",
        "encoding": "encoder",
        "mix-dj": "djmixer",
        "original year": "originaldate",
        "origdate": "originaldate",
        "originator": "encoder",
        "unsyncedlyrics": "lyrics",
        "upc": "barcode",
        "url": "url_lyrics_site",
        "year": "date",
    }

    # tags which become TXXX (flac / ID3 TXXX)
    txxx = {
        "acoustid_id": "AcoustID",
        "art direction": "art direction",
        # "artists":"artists", # generate in-line
        "asin": "ASIN",
        "barcode": "BARCODE",
        "beatintensity": "beatintensity",
        "catalognumber": "catalognumber",
        "design/illustration": "design/illustration",
        "digitize_date": "Digitize Date",
        "digitize_info": "Digitize Info",
        "editor": "editor",
        "encoder": "encoder",
        "ensemble": "ensemble",
        "graphic design": "graphic design",
        "illustration": "illustration",
        "instrument arranger": "instrument arranger",
        "iswc": "iswc",
        "liner notes": "liner notes",
        "mcn": "MCN",
        "musicbrainz_albumartistid": "MusicBrainz Album Artist Id",
        "musicbrainz_albumcomment": "MusicBrainz Album Comment",
        "musicbrainz_albumid": "MusicBrainz Album Id",
        "musicbrainz_albumtype": "MusicBrainz Album Type",
        # incorrect, should be generated in-line
        "musicbrainz_artistid": "MusicBrainz Artist Id",
        "musicbrainz_discid": "MusicBrainz Disc Id",
        "musicbrainz_recordingid": "MusicBrainz Recording Id",
        "musicbrainz_releasegroupid": "MusicBrainz Release Group Id",
        # "musicbrainz_trackid":"MusicBrainz Track Id", # this is the UFID
        # "musicbrainz_trackid":"MusicBrainz Release Track Id", # I don't have this right
        "musicbrainz_releasetrackid": "MusicBrainz Release Track Id",
        "musicbrainz_trmid": "MusicBrainz TRM Id",
        "musicbrainz_workid": "MusicBrainz Work Id",
        "organization": "Organization",
        "packaging": "Packaging",
        "photography": "photography",
        "publisher": "Publisher",
        "releasecountry": "MusicBrainz Album Release Country",
        "releasestatus": "MusicBrainz Album Status",
        "releasetype": "Release Type",
        "scale": "scale",
        "script": "SCRIPT",
        "tag": "tag",
        "time_signature": "time signature",
        "tuning": "tuning",
        "vocal arranger": "vocal arranger",
        "work": "work",
        "writer": "writer",
        "bmi id": "bmi",
        "ascap id": "ascap",
        "apra id": "apra",
        "gema id": "gema",
        "jasrac id": "jasrac",
        "sacem id": "sacem",
        "socan id": "socan",
        "cash id": "cash",
        "sesac id": "sesac",
    }

    # tags we translate into TIPL (flac / ID3 TIPL)
    tipl = {
        "arranger": "arranger",
        "DJ-mix": "djmixer",
        "engineer": "engineer",
        "mastering": "mastering",
        "misc": "misc",
        "mix": "mixer",
        "mixer": "mixer",
        "producer": "producer",
        "programming": "programming",
    }

    # mapping ID3 to flac
    xlist = {
        "TALB": "album",
        "TBPM": "bpm",
        "TCMP": "compilation",
        "TCOM": "composer",
        "TCON": "genre",
        "TCOP": "copyright",
        "TDOR": "originalyear",
        "TDRC": "date",
        "TENC": "encoder",
        "TEXT": "lyricist",
        # "TIT1": "grouping",
        "TIT2": "title",
        "TIT3": "subtitle",
        "TKEY": "key",
        "TLAN": "language",
        "TMED": "media",
        # "TMOO":"mood", # comma seperated values
        "TOAL": "original_album",
        "TPE1": "artist",
        "TPE2": "albumartist",
        "TPE3": "conductor",
        "TPE4": "remixer",
        "TPOE": "original_artist",
        "TPOS": "discnumber",
        "TPUB": "label",
        "TRCK": "tracknumber",
        "TSO2": "albumartistsort",
        "TSOC": "composersort",
        "TSOP": "artistsort",
        "TSOT": "titlesort",
        # "TSRC":"isrc", # / separated values
        "TSSE": "encoder",
        "TSST": "discubtitle",
        "USLT": "lyrics",
    }

    xlistm4a = {
        # not going from m4a to FLAC yet
    }

    # would using map() work for these?
    for k, v in list(txxx.items()):
        xlist["TXXX:%s" % v] = k
    for k, v in list(wxxx.items()):
        xlist["WXXX:%s" % v] = k

    # keep this in sync with discogs
    validgrouping = [
        "Animation",
        "Anime",
        "Baroque",
        "Blues",
        "Brass & Military",
        "Children's",
        "Classical",
        "Electronic",
        "Folk",
        "Folk, World, & Country",
        "Fringe Rock",
        "Funk / Soul",
        "Game",
        "Hip Hop",
        "Indie",
        "Jazz",
        "Latin",
        "Non-Music",
        "Pop",
        "Reggae",
        "Rock",
        "Stage & Screen",
        "World music",
    ]

    # keep this in sync with discogs
    validgenre = [
        "Aboriginal",
        "Abstract",
        "Acid",
        "Acid House",
        "Acid Jazz",
        "Acoustic",
        "African",
        "Afro-Cuban",
        "Afro-Cuban Jazz",
        "Afrobeat",
        "Alternative Rock",
        "Ambient",
        "Arena Rock",
        "Art Rock",
        "Audiobook",
        "Avant-garde Jazz",
        "Avantgarde",
        "Ballad",
        "Baroque",
        "Beat",
        "Big Band",
        "Big Beat",
        "Bluegrass",
        "Blues Rock",
        "Bollywood",
        "Bossa Nova",
        "Bossanova",
        "Brass Band",
        "Breakbeat",
        "Breakcore",
        "Breaks",
        "Brit Pop",
        "Broken Beat",
        "Carnatic",
        "Celtic",
        "Cha-Cha",
        "Chanson",
        "Chinese Classical",
        "Classic Rock",
        "Classical",
        "Comedy",
        "Conscious",
        "Contemporary",
        "Contemporary Jazz",
        "Cool Jazz",
        "Country",
        "Country Rock",
        "Cut-up/DJ",
        "Dancehall",
        "Dark Ambient",
        "Darkwave",
        "Deep House",
        "Dialogue",
        "Disco",
        "Dixieland",
        "Doo Wop",
        "Downtempo",
        "Drone",
        "Drum n Bass",
        "Dub",
        "Dub Techno",
        "Dubstep",
        "EBM",
        "Early",
        "Easy Listening",
        "Education",
        "Educational",
        "Electro",
        "Electro House",
        "Emo",
        "Enka",
        "Ethereal",
        "Euro House",
        "Europop",
        "Experimental",
        "Fictitious artist",
        "Field Recording",
        "Flamenco",
        "Folk",
        "Folk Rock",
        "Folk, World, & Country",
        "Free Funk",
        "Free Improvisation",
        "Free Jazz",
        "Freestyle",
        "Fringe Rock",
        "Funk",
        "Funk / soul",
        "Funk Metal",
        "Fusion",
        "Future Jazz",
        "Gamelan",
        "Gangsta",
        "Garage House",
        "Garage Rock",
        "Glam",
        "Glitch",
        "Gospel",
        "Goth Rock",
        "Griot",
        "Grunge",
        "Happy Hardcore",
        "Hard Bop",
        "Hard House",
        "Hard Rock",
        "Hard Trance",
        "Hardcore",
        "Heavy Metal",
        "Hi NRG",
        "Hindustani",
        "Hip Hop",
        "Hip-House",
        "House",
        "IDM",
        "Illbient",
        "Indian Classical",
        "Indie Pop",
        "Indie Rock",
        "Industrial",
        "Instrumental",
        "Interview",
        "J-pop",
        "Jazz",
        "Jazz-Funk",
        "Jazz-Rock",
        "Jazzdance",
        "Jazzy Hip-Hop",
        "Jungle",
        "Krautrock",
        "Latin",
        "Latin Jazz",
        "Leftfield",
        "Lo-Fi",
        "Louisiana Blues",
        "Lounge",
        "Mambo",
        "Math Rock",
        "Medieval",
        "Minimal",
        "Mod",
        "Modal",
        "Modern",
        "Modern Classical",
        "Modern Electric Blues",
        "Monolog",
        "Mouth Music",
        "Music Hall",
        "Musical",
        "Musique Concr\xe8te",
        "Neo Soul",
        "Neo-Classical",
        "Neo-Romantic",
        "Neofolk",
        "New Beat",
        "New Wave",
        "Noise",
        "Novelty",
        "Nu Metal",
        "Opera",
        "Overtone Singing",
        "P.Funk",
        "Parody",
        "Piano Blues",
        "Pipe & Drum",
        "Poetry",
        "Pop",
        "Pop Punk",
        "Pop Rap",
        "Pop Rock",
        "Post Bop",
        "Post Rock",
        "Post-Modern",
        "Post-Punk",
        "Power Electronics",
        "Power Pop",
        "Prog Rock",
        "Progressive House",
        "Progressive Trance",
        "Promotional",
        "Psy-Trance",
        "Psychedelic",
        "Psychedelic Rock",
        "Psychobilly",
        "Punk",
        "Rap",
        "Radioplay",
        "Ragga HipHop",
        "Ragtime",
        "Reggae",
        "Reggae-Pop",
        "Religious",
        "Renaissance",
        "Rhythm & Blues",
        "RnB/Swing",
        "Rock",
        "Rock & Roll",
        "Rockabilly",
        "Rocksteady",
        "Romantic",
        "Roots Reggae",
        "Rumba",
        "Salsa",
        "Schlager",
        "Score",
        "Screw",
        "Shoegaze",
        "Shoegazer",
        "Ska",
        "Skiffle",
        "Smooth Jazz",
        "Soft Rock",
        "Soul",
        "Soul-Jazz",
        "Soundtrack",
        "Southern Rock",
        "Space Rock",
        "Space-Age",
        "Speech",
        "Speed Metal",
        "Spoken Word",
        "Stoner Rock",
        "Surf",
        "Swing",
        "Symphonic Rock",
        "Synth-pop",
        "Tango",
        "Tech House",
        "Techno",
        "Theme",
        "Thrash",
        "Trance",
        "Tribal",
        "Tribal House",
        "Trip Hop",
        "Twelve-tone",
        "UK Garage",
        "Vocal",
        "World music",
    ]

    bogustags = [
        "*england\u2192north east\u2192wallsend",
        "1",
        "1 10 188043 183 17153 34783 54830 72970 97673 116825 128263 157073 171433",
        "1 13 165900 150 7672 22647 34612 48720 59280 74602 87545 95495 107182 131087 141522 153710",
        "10 cd",
        "10th anniversary commemorative edition",
        "1234",
        "134a",
        "17",
        "17 rock",
        "24 nights",
        "255",
        "27 club",
        "28 gun bad boy",
        "29bpm",
        "311",
        "3a46633b-26ed-4418-a029-ab77de3ccfae",
        "50 cent",
        "7 58",
        "9396b898-78c3-6449-2cd8-3279bffa57ef",
        "<unknown>",
        "[anon.]",
        "_fix me_",
        "a gold disc artist",
        "aaa",
        "abba",
        "academy award winner",
        "al",
        "albarn",
        "albert hammond",
        "alicia de larrocha",
        "american 21st century opera aria rock",
        "americana/60s/tom rush/these days/singer-songwriter/acoustic/folk/singer songwriter",
        "amos lee",
        "andrew mann",
        "andy white",
        "anon",
        "anthony newman",
        "anuna choral celtic irish ireland",
        "aor",
        "aor classic rock",
        "appalachian",
        "archive",
        "automod ng",
        "awesomename",
        "b7005bb9-fcd9-4d06-8c39-c5ef11275ef1",
        "bach",
        "bach goldberg variations",
        "bach the goldberg variations",
        "band",
        "bbc",
        "bbc radiophonic workshop",
        "beachcomer s windowsill",
        "beatbox piano opera jam - pottsy upstairs @cosmo bar",
        "ben gibbard",
        "bennie and the jets",
        "best",
        "best of",
        "best songs ever",
        "black secret technology",
        "blank and jones",
        "blow the house down",
        "bogus",
        "bogus artist",
        "bonus",
        "bootleg",
        "border reiver",
        "bowie",
        "box",
        "box set",
        "brahms",
        "brill building",
        "bristol",
        "buzuq",
        "bwv 988",
        "c2d8e351-129f-44ce-970a-bde652f9ed55",
        "can't tell if awesomename... or sillyname",
        "cd album",
        "cd extra",
        "cd-text eng",
        "cease2xist",
        "central european traditions",
        "check it",
        "childhood nostalgia",
        "children s",
        "children's",
        "clapton",
        "classic soul r b",
        "clean up",
        "cleaned up",
        "cleanup",
        "clive farrington",
        "cock robin",
        "colin angus",
        "columbia",
        "compilation",
        "complete",
        "complete mozart edition",
        "composer",
        "compositeur",
        "concerto for orchestra",
        "cotm",
        "cover versions",
        "covered and sampled",
        "covered by 10",
        "covered by 11",
        "covered by 16",
        "covered by 22",
        "covered by 3",
        "covered by 4",
        "covered by 5",
        "covered by 6",
        "covered by 7",
        "covered by 8",
        "covered by glee",
        "css",
        "cumbia",
        "damon",
        "dan stephens",
        "data",
        "dave 1991",
        "dave 2003",
        "dead man s party",
        "default",
        "deisgner graphic",
        "demon. acid house",
        "die walkure",
        "digital hardcore",
        "discoth que",
        "do not split",
        "dock of the bay",
        "dr10",
        "dr11",
        "dr12",
        "dr14",
        "dr5",
        "dr6",
        "dr8",
        "dr9",
        "dream on",
        "drew",
        "drsaunde",
        "dvd",
        "dylan bootleg series",
        "d\xe9i\xe0 - sa fonda august 1998 - and a once for the hp sauce",
        "d\xfan laoghaire",
        "e3",
        "ebeneezer goode",
        "ed3318f1-fe4a-460a-9ab7-ae7175848928",
        "eden of the east",
        "elenor",
        "elton-john",
        "elvis",
        "emi",
        "en-tact",
        "england\u2192north east\u2192wallsend",
        "entact",
        "eric clapton",
        "ethnic",
        "every breath you take",
        "fannybe tender with my love",
        "feist",
        "fever",
        "fixme",
        "fixme label mess",
        "fixme ngs?",
        "florence and the machine",
        "format-sacd",
        "fran ais",
        "frequently covered",
        "fuel up",
        "gema ng",
        "girls on film",
        "go west",
        "gore kutherrie",
        "gorillaz graham coxon coxon song 2 woo hoo",
        "gould",
        "gould inventions",
        "graphique designer",
        "greatest hits",
        "hayes",
        "he aint heavy",
        "her expression is like shes thinking something dumb",
        "hidden track",
        "home",
        "how sweet it is",
        "how sweet it is to be lovered by you",
        "http://127.0.0.1:8000/openalbum?id=b8861fc7-75ed-415a-bd52-c6d8e10662ae&t=1331371978",
        "http://127.0.0.1:8000/opennat?id=66543810-fe10-4d35-a08c-0ab079d34932",
        "http://musicbrainz.org/release-group/8f174877-ffc4-39b9-b247-a39fff4097a1",
        "http://musicbrainz.org/release/1e14b2d6-8652-3dcc-b60b-4fb5fe79e024",
        "i am a party girl here is my soundtrack",
        "icon",
        "idle fret",
        "if you talk in your sleep",
        "in gorbachev we trust",
        "in the flesh",
        "inconnu",
        "incredible lp",
        "indieindie",
        "inditeronica",
        "inditronica",
        "isabel monteiro",
        "jaime harding",
        "jasrac lost iswc",
        "jasrac ng",
        "jasrac-no-iswc",
        "jeff beck",
        "jello biafra",
        "jenny lewis",
        "john foxx",
        "joe ray",
        "jon brooks",
        "kasabian",
        "katy perry",
        "kh\xf6\xf6mei",
        "kind of magic",
        "king's college",
        "king's x",
        "kurt cobain",
        "lana del rey",
        "langham 1 studio bbc",
        "language",
        "language",
        "legendary",
        "lgm501",
        "liam o maonlai",
        "library",
        "library music",
        "likedis auto",
        "lily",
        "lincoln park",
        "live in concert",
        "living in a box",
        "lock",
        "look after you",
        "looks like a special purpose artist but is not",
        "loren maazel",
        "lost",
        "love's a loaded gun",
        "lp",
        "marcus vere",
        "marion",
        "masterworks",
        "max",
        "mbs-333",
        "mbube",
        "medley a b",
        "merge",
        "merge me",
        "mergeme",
        "messe h-moll",
        "metallica",
        "michael floreale",
        "misc",
        "mixed media",
        "mono",
        "moose!",
        "more",
        "mostly known by the cover",
        "motown 1",
        "mountainremixes",
        "move any mountain",
        "mpb",
        "mrc",
        "mta records",
        "multiple ipi",
        "multiple iswc",
        "multiple release dates",
        "music",
        "music hall",
        "music production",
        "my blue heaven",
        "my favolite",
        "my morning jacket",
        "n2",
        "n3",
        "naim edge",
        "needs merging into [no artist]",
        "needs multiple titles support",
        "newvalue",
        "nice",
        "nirvana",
        "no copyright info3",
        "no doubt",
        "none",
        "nwobhm",
        "oasis",
        "one beatles",
        "opus 57",
        "other",
        "othergeneral rock",
        "paul weller",
        "paul-simon",
        "persistence of time",
        "phil spector",
        "phonetic phail",
        "phorever people",
        "phorward",
        "pittsburgh symphony orchestra",
        "play",
        "podcast",
        "pretzelbodylogic",
        "prince revolution",
        "pro-gen",
        "pro>gen",
        "progen",
        "raggamuffin",
        "rerip 80s",
        "rerip grunge",
        "rerip pop rock",
        "rerip soundtrack",
        "richard darbyshire",
        "richard west",
        "robin",
        "roger waters",
        "rory gallagher",
        "ry cooder",
        "sabina",
        "sacred cows",
        "sananda maitreya",
        "satanic",
        "script-deva",
        "script-geor",
        "seen live",
        "series title as author name",
        "series-mozart-complete works-philips",
        "shake your rump",
        "shamen",
        "she s got a way",
        "should be public domain",
        "sillyname",
        "simon-garfunkel",
        "siple twist of fate",
        "slow fox",
        "snoop dogg",
        "so i married",
        "sofeaturing rock",
        "software company as artist",
        "sound engineer",
        "special purpose artist",
        "splitme",
        "star trek soundtracks",
        "star wars",
        "stay awake",
        "stealing sheep",
        "steel pulse",
        "stiff little fingers",
        "stock two smoking barrels",
        "stop merging crap so my tags get fucked up",
        "stornowayband",
        "suboptimal credits",
        "super trouper",
        "sweet baby james",
        "sweet bands",
        "tarantino",
        "teater konsert",
        "teenage dream",
        "tell me",
        "the academy",
        "the beatles",
        "the blues brothers",
        "the jam",
        "the netherlands",
        "the police",
        "the promise",
        "the shamen",
        "the sound",
        "the unforgiving",
        "the very best of",
        "the way i feel",
        "the-beatles",
        "the-rolling-stones",
        "theoldblindman",
        "this is the time",
        "thomas bangalter",
        "tilson",
        "tim finn",
        "tina-turner",
        "tmr",
        "to fix bootlegs",
        "todo-works",
        "tough monkey records",
        "trixie",
        "uk single cd1",
        "unclassifiable",
        "unicode-non-bmp",
        "unkle",
        "unknown",
        "ur so fail",
        "user defined",
        "various artists",
        "vbyjtiicc a6pamrvplxdepb02k-",
        "verve",
        "vinyl",
        "violent femmes",
        "volume 15",
        "want to listen",
        "wantlist-acid2",
        "ween(er)",
        "weezer",
        "what s the matter here",
        "when in rome",
        "whimsically inclined",
        "wir sind helden",
        "work",
        "wp musicians",
        "wrong guess case",
        "wrong puid",
        "x",
        "xtc",
        "zorbing",
        "zz unknown genre",
        "\u0440\u043e\u0441\u0441\u0438\u044f",
        "\u65e5\u672c",
        "\u6e0b\u8c37\u7cfb",
        "discogs_price",
    ]
